[versions]
awssdk = "2.41.29"
mockito = "5.21.0"
jackson2 = "2.21.0"
jackson3 = "3.1.0-rc1"

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }

# Applies analysis tools including checkstyle and OWASP Dependency checker.
hmcts-check = { id = 'uk.gov.hmcts.java', version = '0.12.67' }

[bundles]

[libraries]
lombok                  = { group = "org.projectlombok", name = "lombok", version = "1.18.42" }

jakarta-validation      = { group = "jakarta.validation", name = "jakarta.validation-api", version = "3.1.1" }
swagger-annotations     = { group = "io.swagger.core.v3", name = "swagger-annotations", version = "2.2.42" }

commons-collection4     = { group = 'org.apache.commons', name = 'commons-collections4', version = "4.5.0" }
commons-lang3           = { group = "org.apache.commons", name = "commons-lang3", version = "3.20.0" }

jackson2-core            = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson2" }
jackson2-databind        = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson2" }
jackson2-jsr310          = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson2" }

jackson2-annotations    = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version = "2.21" }

jackson3-core          = { group = "tools.jackson.core", name = "jackson-core", version.ref = "jackson3" }
jackson3-databind      = { group = "tools.jackson.core", name = "jackson-databind", version.ref = "jackson3" }

slf4j                   = { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }
slf4j-log4j2            = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version = "2.25.3" }
aws-lambda-log4j2       = { group = "com.amazonaws", name = "aws-lambda-java-log4j2", version = "1.6.2" }

mockito-core            = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit           = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }

eclipse-store-spring    = { group = 'software.xdev', name = 'spring-data-eclipse-store', version = '2.5.3' }

aws-lambda-core         = { group = "com.amazonaws", name = "aws-lambda-java-core", version = "1.4.0" }
aws-lambda-events       = { group = "com.amazonaws", name = "aws-lambda-java-events", version = "3.16.1" }

aws-http-jdk            = { group = "software.amazon.awssdk", name = "url-connection-client", version.ref = "awssdk"}

aws-dynamobb            = { group = "software.amazon.awssdk", name = "dynamodb", version.ref = "awssdk" }
aws-dynamobb-enh        = { group = "software.amazon.awssdk", name = "dynamodb-enhanced", version.ref = "awssdk" }
aws-sts                 = { group = "software.amazon.awssdk", name = "sts", version.ref = "awssdk" }

aws-cdk                 = { group = "software.amazon.awscdk", name = "aws-cdk-lib", version = "2.238.0" }
constructs              = { group = "software.constructs", name = "constructs", version = "[10.0.0,11.0.0)" }

